const BAD_REQUEST = "400: Invalid request";
const BAD_REQUEST_CODE = 400;
const NOT_FOUND = "404: Not found";
const NOT_FOUND_CODE = 404;
const INTERNAL_SERVER_ERROR = "500: Internal server error";
const INTERNAL_SERVER_ERROR_CODE = 500;
const CONFLICT = "409: Conflict";
const CONFLICT_CODE = 409;
const UNAUTHORIZED = "401: Unauthorized";
const UNAUTHORIZED_CODE = 401;
const FORBIDDEN = "403: Forbidden";
const FORBIDDEN_CODE = 403;

module.exports = {
  BAD_REQUEST,
  BAD_REQUEST_CODE,
  NOT_FOUND,
  NOT_FOUND_CODE,
  INTERNAL_SERVER_ERROR,
  INTERNAL_SERVER_ERROR_CODE,
  CONFLICT,
  CONFLICT_CODE,
  UNAUTHORIZED,
  UNAUTHORIZED_CODE,
  FORBIDDEN,
  FORBIDDEN_CODE,
};
